name: Deploy to AWS EC2 (Amazon Linux)

on:
  push:
    branches:
      - dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "54.163.17.7"
          username: ec2-user
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            SHA256:thUif5JDsusQKaXMQmNkM14UPtmLUgN870clhFmA32o prpareek21@gmail.com
            -----END RSA PRIVATE KEY-----
          script: |
            cd /home/ec2-user/Webshop_Group24/backend/cloudbackend  # Change to your project directory
            git pull origin dev
            source /home/ec2-user/venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
